Add EditProfile screen and styles
redacademy/nodal-winter-2018 pull request #59
Opened 2018-03-16 04:35 UTC by NCMoseley

Boilerplate code

2018-03-16 18:33 UTC, siddharthparmar7 requested changes
Good work, Nate!!

Please remove all the commented out code. If you are going to use it later, then save it somewhere else.

Thank you!

2018-03-16 21:33 UTC, NCMoseley commented
Comments removed! (except this one)

2018-03-16 23:13 UTC, siddharthparmar7 requested changes
/* global require */ // This is to avoid a linting error with 'require'

remove that comment from js/screens/EditProfile/EditProfileContainer.js file.

Otherwise, it looks good. Thank you!

2018-03-18 01:12 UTC, NCMoseley commented
Comment deleted.

2018-03-19 17:43 UTC, siddharthparmar7 requested changes
Thank you, Nate! 

Once the requested change is made, I will merge this branch.

2018-03-19 17:43 UTC, siddharthparmar7 commented on js/screens/EditProfile/EditProfile.js
> +  func: PropTypes.string.isRequired
I believe func is a function, not a string. Talk to me if you have any questions.

2018-03-19 20:16 UTC, NCMoseley commented
OK all good, thanks

2018-03-19 23:23 UTC, siddharthparmar7 approved these changes
Thank you!

2018-03-19 23:23 UTC, merged