Add chips logic and styles
redacademy/nodal-winter-2018 pull request #67
Opened 2018-03-18 00:31 UTC by NCMoseley

2018-03-19 18:59 UTC, siddharthparmar7 requested changes
Don't forget to assign yourself to this issue.
Also, please resolve your branch conflict. 
Thank you!

2018-03-19 18:59 UTC, siddharthparmar7 commented on js/components/Chips/Chips.js
> +const Chips = ({
Add propTypes for the props that you are receiving.

2018-03-19 18:59 UTC, siddharthparmar7 commented on js/components/Chips/ChipsContainer.js
> +  constructor() {
if you are receiving props don't forget to pass "props" in your constructor and in your super.

2018-03-19 18:59 UTC, siddharthparmar7 commented on js/components/Chips/ChipsContainer.js
> +  chips: PropTypes.array,
add .isRequired, if you can not do that then add default propType for all your props

2018-03-19 18:59 UTC, siddharthparmar7 commented on js/components/Chips/styles.js
> +import { colors, typography } from "../../config/styles";
I don't see you are using colors, so remove it please

2018-03-19 18:59 UTC, siddharthparmar7 commented on js/components/Chips/styles.js
> +const { height, width } = Dimensions.get("window");
I don't see you are using height so remove it, please.

2018-03-19 18:59 UTC, siddharthparmar7 commented on js/screens/Profile/Profile.js
>  import PropTypes from "prop-types";
remove importing propTypes if you are not using it.

2018-03-19 18:59 UTC, siddharthparmar7 commented on js/screens/Profile/styles.js
> +const { height, width } = Dimensions.get("window");
Remove height if you are not using it.

2018-03-19 21:19 UTC, NCMoseley commented
Ok, looking good.

2018-03-19 23:38 UTC, siddharthparmar7 requested changes
Thank you! 

make these small changes soon and let me know so I can approve it.

2018-03-19 23:38 UTC, siddharthparmar7 commented on js/screens/Profile/ProfileContainer.js
> +ProfileContainer.propTypes = {
You are not receiving any props for ProfileContainer so you don't need to check for propTypes. Also, don't import it.

2018-03-19 23:38 UTC, siddharthparmar7 commented on js/screens/Profile/styles.js
> +const { height, width } = Dimensions.get("window");
remove height if you are not using it.

2018-03-19 23:38 UTC, siddharthparmar7 commented on App.js
> + * https://github.com/facebook/react-native
while you are at it, remove line 3 and replace it with your project's GitHub link.

2018-03-20 00:28 UTC, NCMoseley commented
: |

2018-03-20 16:11 UTC, siddharthparmar7 approved these changes
Thank you! Nate!

2018-03-20 16:11 UTC, merged