Create Loading Screens for Matching
redacademy/nodal-winter-2018 pull request #87
Opened 2018-03-21 00:01 UTC by NCMoseley

2018-03-21 19:01 UTC, siddharthparmar7 requested changes
Thank you, Nate!

If you have any confusions, please ask me.

Thank you!

2018-03-21 19:01 UTC, siddharthparmar7 commented on js/screens/MatchScreenLoading/MatchScreenLoadingContainer.js
> +    this.state = {
Please use Redux store instead of the component state.

2018-03-22 21:55 UTC, NCMoseley commented
Please review changes. Thank you very much.

2018-03-22 23:40 UTC, siddharthparmar7 requested changes
Please make the requested changes.

Thank you!

2018-03-22 23:40 UTC, siddharthparmar7 commented on js/screens/MatchScreenLoading/MatchScreenLoadingContainer.js
> +    this.state = {
Hi Nate,

Please use Redux store instead of the component state. Thank you.

2018-03-23 02:54 UTC, NCMoseley commented
Please review. Thanks

2018-03-23 16:22 UTC, siddharthparmar7 approved these changes
Thank you! Nate!

Good work.

2018-03-23 16:22 UTC, merged